export type Range = {
    alert: boolean;
    min: number;
    max: number;
};
export type UsernFollowerDetail = {
    user_id: string;
    user_phone: string;
    user_name: string;
    is_disabled: boolean;
    fcm_token: string;
    created_at: number;
    updated_at: number;
    password: string;
    roles: Array<"user" | "admin" | "physician">;
    is_logged_in: boolean;
    last_logged_status_at: number;
    wrong_password_count: number;
    last_password_attempt_at: number;
    image: string;
    updated_by: string;
    created_by: string;
    source: string;
    logo: string;
};
export type Followers = {
    code: number;
    total_page: number;
    page_id: number;
    data: {
        id: string;
        followers: [];
        user_id: string;
        user_name: string;
        password: string;
        roles: string[];
        health_insurance_code: string | null;
        created_at: number;
        updated_at: number;
        is_disabled: boolean;
        dob: string | null;
        gender: string | null;
        code: string | null;
        address: string | null;
        temp_range: Range;
        hr_range: Range;
        nibp_range: {
            low_pressure: Range;
            high_pressure: Range;
            automatic_interval: number;
        };
        spo2_range: Range;
        pr_range: Range;
        resp_range: Range;
        alarm_interval: number;
        auto_save: number;
        ethnic: string | null;
        religion: string | null;
        relation_with_me: string | null;
        occupation: string | null;
        nationality: string | null;
        phone: string;
        is_default: false;
        image: string | null;
        device_mode: string | null;
        device_mode_value: string | null;
        partner: string | null;
        patient_partner_id: string | null;
        allergies: string | null;
        pregnancy_status: string | null;
        special_needs: string | null;
        patient_state: string | null;
        patient_age: string | null;
        patient_weight: string | null;
        patient_height: string | null;
        last_record_created_at: string | null;
        ecg_gain_scale: string | null;
        resp_gain_scale: string | null;
    }[];
};
